# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 12:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualization', '0002_node_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_local', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('deleted', models.BooleanField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celery_task', models.CharField(max_length=255, unique=True)),
                ('is_local', models.BooleanField()),
                ('rendered_code', models.TextField()),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Contestant')),
                ('desk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Desk')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Node')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRunSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_admin.Task')),
            ],
        ),
        migrations.AddField(
            model_name='taskrun',
            name='run_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_admin.TaskRunSet'),
        ),
    ]
