# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0003_auto_created_at_for_taskrunset'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
