# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 19:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_admin', '0004_taskrun_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrunset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
