# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0005_taskrunset_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrunset',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taskrunset', to=settings.AUTH_USER_MODEL),
        ),
    ]
