# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0007_auto_20170303_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
