# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0008_auto_20170303_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrunset',
            name='task',
        ),
        migrations.AddField(
            model_name='taskrunset',
            name='code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrunset',
            name='is_local',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
