# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0010_taskrunset_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrun',
            name='return_code',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrun',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskrun',
            name='status',
            field=models.CharField(db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='stderr',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='taskrun',
            name='stdout',
            field=models.TextField(blank=True),
        ),
    ]
