# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0011_auto_20170425_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='taskrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
