# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0012_auto_20170425_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='return_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
