# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0013_auto_20170425_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrun',
            name='celery_task',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
