# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0014_auto_20170425_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrunset',
            name='name',
            field=models.TextField(blank=True),
        ),
    ]
