# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0018_taskrunset_summary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='TaskTemplate',
        ),
    ]
