# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_admin', '0019_auto_20170623_0316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskRunSet',
            new_name='Task',
        ),
        migrations.RenameField(
            model_name='TaskRun',
            old_name='run_set',
            new_name='task',
        ),
    ]
