# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('property_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='desk',
            name='active_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desk', to='visualization.Node'),
        ),
        migrations.AddField(
            model_name='desk',
            name='contestant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desk', to='visualization.Contestant'),
        ),
        migrations.AddField(
            model_name='desk',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Room'),
        ),
    ]
