# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='username',
            field=models.CharField(default='root', max_length=20),
            preserve_default=False,
        ),
    ]
