# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='number',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='mac_address',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='property_id',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
