# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0003_position'),
        ('visualization', '0002_node_username'),
    ]

    operations = [
    ]
