# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 00:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0005_auto_20170224_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desk',
            name='position',
        ),
        migrations.AddField(
            model_name='desk',
            name='angle',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(359), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='desk',
            name='x',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='desk',
            name='y',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
