# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 01:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0006_auto_20170225_0001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set([('country', 'number')]),
        ),
    ]
