# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0007_auto_20170225_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='number',
            field=models.IntegerField(default=1),
        ),
    ]
