# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('visualization', '0008_auto_20170225_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNode',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('mac_address', models.CharField(db_index=True, max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('username', models.CharField(max_length=20)),
                ('property_id', models.CharField(db_index=True, max_length=20)),
                ('connected', models.BooleanField(default=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'verbose_name': 'historical node',
                'get_latest_by': 'history_date',
            },
        ),
        migrations.AddField(
            model_name='node',
            name='connected',
            field=models.BooleanField(default=False),
        ),
    ]
