# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 15:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0010_auto_20170309_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='x',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='desk',
            name='y',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
