# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-18 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0013_auto_20170318_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desk',
            name='active_node',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desk', to='visualization.Node'),
        ),
        migrations.AlterField(
            model_name='desk',
            name='contestant',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desk', to='visualization.Contestant'),
        ),
        migrations.AlterField(
            model_name='node',
            name='property_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
