# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-30 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0018_nodegroup'),
        ('visualization', '0018_node_last_task'),
    ]

    operations = [
    ]
