# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-20 01:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0019_merge_20170530_1915'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='contestant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
