# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-23 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0022_auto_20170623_0627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Room',
            new_name='Zone',
        ),
        migrations.RenameField(
            model_name='desk',
            old_name='room',
            new_name='zone',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='gender',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='desk',
            unique_together=set([('zone', 'number')]),
        ),
    ]
