# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 06:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0027_add_code_to_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set([('team', 'number')]),
        ),
    ]
