# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-23 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0029_auto_20170723_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestant',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
