# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualization', '0030_auto_20170723_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=640)),
                ('height', models.FloatField(default=480)),
                ('name', models.CharField(max_length=40, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='zone',
            name='x',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='y',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='zone',
            name='height',
            field=models.FloatField(default=240),
        ),
        migrations.AlterField(
            model_name='zone',
            name='width',
            field=models.FloatField(default=320),
        ),
        migrations.AddField(
            model_name='zone',
            name='floor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='visualization.Floor'),
        ),
    ]
