# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 12:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('visualization', '0013_auto_20170318_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('connected', models.BooleanField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualization.Node')),
            ],
        ),
    ]
